apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: node-group-controller-manager
  name: group-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-group-controller-manager
  namespace: group-system
  labels:
    control-plane: node-group-controller-manager
spec:
  selector:
    matchLabels:
      control-plane: node-group-controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: node-group-controller-manager
    spec:
      serviceAccountName: node-group-controller-manager
      containers:
      - command:
        - /bin/node-group-controller-manager
        image: kubeedge.io/node-group-controller-manager:latest
        imagePullPolicy: IfNotPresent
        name: node-group-controller-manager
      terminationGracePeriodSeconds: 10
