# permissions for end users to edit propagationpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: propagationpolicy-editor-role
rules:
- apiGroups:
  - policy.harmonycloud.io
  resources:
  - propagationpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.harmonycloud.io
  resources:
  - propagationpolicies/status
  verbs:
  - get
