apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-group-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-group-manager-role
subjects:
- kind: ServiceAccount
  name: node-group-controller-manager
  namespace: group-system
