
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: node-group-manager-role
rules:
- apiGroups: ['*']
  resources: ['*']
  verbs: ["get", "watch", "list", "create", "update", "delete"]
- nonResourceURLs: ['*']
  verbs: ["get"]
