## Append samples you want in your CSV to this file as resources ##
resources:
- cluster.harmonycloud.io_v1alpha1_cluster.yaml
- policy_v1alpha1_propagationpolicy.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
